### ISSUE TITLE
Question: Change language to format or format-language?

### ISSUE THREAD

**Issue by svx** [testthedocs/ttd.training-docs-basics#1]
@polyester 
Currently we use *language* as term we use to explain reST, markdonw and so on, this could confuse people, should we re-name it to something like format or format-language?

**Comment by polyester** [comment]
I would go with the official term "markup format". It's a format, not a language, and markup is the 'official' term. It's a bit formal, but it is easy to find/search.

**Comment by svx** [comment]
done !
