### ISSUE TITLE
Editors

### ISSUE THREAD

**Issue by svx** [testthedocs/ttd.training-docs-basics#6]
List of Editors we want to cover, the idea is to include them into mr.otlet and also have the configs on github.

- [x] Sublime Text 3 ?
- [x] Vim ?
- [x] reText

@polyester what do you think should we add more ? Since that is for beginners we could also add 

- Atom
- Brackets

and could have vim, nano, emacs and other stuff 'just' as a mention and a link to their config ?

For Add-ons:

- git
- reST check
- spell check
- preview
- ?

**Comment by polyester** [comment]
While "vim" is hardly a beginner tool for most, it could be the editor that a coder that just starts writing docs is familiar with, so yes include that.

I would maybe include Brackets as it's a 'simple' editor. I would not include Atom, as it's more or less equivalent with Sublime, but slower. And having two tools with same functionality is just confusing.

add-ons: aren't they different per editor? For sublime, I would say

- enable spellcheck for .rst files
- rst snippets (that includes preview)
- not sure about linter. Once you have it, you can include write-good and rst linters, but it may be more to setup. On the other hand, sublime-linter framework is one of the most useful out there, and many devs will want to have it for flake etcetera as well.

**Comment by svx** [comment]
@polyester I just tested Brackets, seems OK for Markdown, but I miss some things for reST, such as preview and so on.
Also the reST syntax check in Brackets is well, not really there.

IMHO we should skip Brackets.

What do you think ?

**Comment by svx** [comment]
Anyway here the play for it in case we will need it later, you never know:

https://github.com/svx/mr.otlet/blob/ansible_new/builder/ansible/brackets.yml

**Comment by svx** [comment]
Closing this, feel free to re-open for now I say we should stay with Sublime as main editor
